INSERT INTO media (url) VALUES
('images/activated_muscles/female/abdomen/'),
('images/activated_muscles/male/abdomen/'),
('images/activated_muscles/female/biceps/'),
('images/activated_muscles/male/biceps/'),
('images/activated_muscles/female/triceps/'),
('images/activated_muscles/male/triceps/'),
('images/activated_muscles/female/forearm/'),
('images/activated_muscles/male/forearm/'),
('images/activated_muscles/female/shoulder/'),
('images/activated_muscles/male/shoulder/'),
('images/activated_muscles/female/chest/'),
('images/activated_muscles/male/chest/'),
('images/activated_muscles/female/quadriceps/'),
('images/activated_muscles/male/quadriceps/'),
('images/activated_muscles/female/adductor/'),
('images/activated_muscles/male/adductor/'),
('images/activated_muscles/female/trapezius/'),
('images/activated_muscles/male/trapezius/'),
('images/activated_muscles/female/lats/'),
('images/activated_muscles/male/lats/'),
('images/activated_muscles/female/lower_back/'),
('images/activated_muscles/male/lower_back/'),
('images/activated_muscles/female/hamstrings/'),
('images/activated_muscles/male/hamstrings/'),
('images/activated_muscles/female/glutes/'),
('images/activated_muscles/male/glutes/'),
('images/activated_muscles/female/calf/'),
('images/activated_muscles/male/calf/');

INSERT INTO muscle_group (name, fk_male_model_media_ID, fk_female_model_media_ID) VALUES
('Abdômen', 2, 1),
('Bíceps', 4, 3),
('Tríceps', 6, 5),
('Antebraço', 8, 7),
('Ombro', 10, 9),
('Peito', 12, 11),
('Quadríceps', 14, 13),
('Adutor', 16, 15),
('Trapézio', 18, 17),
('Dorsal', 20, 19),
('Lombar', 22, 21),
('Posterior de Coxa', 24, 23),
('Glúteos', 26, 25),
('Panturrilha', 28, 27);

-- Mudar para nome tecnico e nome popular, adicionar campo de "exercicio impersonalizavel" para exs como flexao diamante
INSERT INTO exercise (technical_name, popular_name, description, is_fixed, fk_media_ID) VALUES 
('Extensão de Cotovelo Acima da Cabeça', 'Tríceps Francês', 'Movimento de extensão dos cotovelos com os braços ao lado da cabeça.', 0, NULL),
('Extensão de Cotovelo para Baixo', 'Tríceps Pulley', 'Movimento de extensão dos cotovelos com os braços ao lado do tronco.', 0, NULL),
('Extensão de Cotovelo na Direção da Cabeça', 'Tríceps Testa', 'Movimento de extensão dos cotovelos com os braços à frente da cabeça.', 0, NULL),
('Extensão de Cotovelo para Trás', 'Tríceps Coice', 'Movimento de extensão dos cotovelos com o tronco inclinado e os braços ao lado do tronco.', 0, NULL),
('Extensão de Cotovelos em Supino Fechado', 'Supino com Pegada Fechada', 'Movimento de extensão dos cotovelos e flexão dos ombros estando deitado e com as mãos próximas.', 0, NULL),
('Flexão com Pegada Fechada', 'Flexão Diamante', 'Movimento de extensão dos cotovelos e flexão dos ombros com o corpo paralelo ao solo e as mãos próximas.', 1, NULL),
('Flexão de Cotovelos com Pegada Média', 'Flexão com Pegada Média', 'Movimento de extensão dos cotovelos e flexão dos ombros com o corpo paralelo ao solo e as mãos na largura dos ombros.', 1, NULL),
('Flexão de Cotovelos com Pegada Aberta', 'Flexão com Pegada Aberta', 'Movimento de extensão dos cotovelos e adução horizontal dos ombros com o corpo paralelo ao solo e as mãos afastadas.', 1, NULL),
('Extensão de Cotovelos Atrás do Tronco', 'Tríceps Mergulho', 'Movimento de extensão dos cotovelos e flexão dos ombros com os braços atrás do tronco.', 0, NULL),
('Flexão de Punho', 'Rosca Punho', 'Movimento de flexão dos punhos com as palmas voltadas para cima.', 0, NULL),
('Extensão de Punho', 'Rosca Punho Inversa', 'Movimento de extensão dos punhos com as palmas voltadas para baixo.', 0, NULL),
('Desvio Ulnar', 'Adução de Punho', 'Movimento de adução dos punhos.', 0, NULL),
('Desvio Radial', 'Abdução de Punho', 'Movimento de abdução dos punhos.', 0, NULL),
('Flexão de Dedos', 'Fechamento de Mão', 'Movimento de flexão dos dedos.', 0, NULL),
('Sustentação Isométrica com Flexão de Dedos', 'Sustentação de Peso com as Mãos', 'Posição em que os dedos estão flexionados para sustentar uma carga.', 0, NULL),
('Flexão e Extensão Alternada de Punho com Corda', 'Roller de Punho', 'Movimento de enrolar e desenrolar uma corda com peso usando os punhos.', 1, NULL),
('Flexão de Cotovelo ao Lado do Tronco', 'Rosca Direta Tradicional', '', 0, NULL),
('Flexão de Cotovelo à Frente do Tronco Apoiado', 'Rosca Scott', '', 0, NULL),
('Flexão de Cotovelo à Frente do Tronco Deitado', 'Rosca Spider', '', 0, NULL),
('Flexão de Cotovelo Atrás do Tronco', 'Rosca Direta Inclinada', '', 0, NULL), 
('Flexão de Cotovelo Apoiado na Perna', 'Rosca Concentrada', '', 0, NULL),
('Flexão de Cotovelo ao Lado da Cabeça', 'Rosca Cruz', '', 0, NULL),
('Flexão de Cotovelo na Polia Alta', 'Rosca na Polia Alta', '', 0, NULL);
