INSERT INTO media (url) VALUES
('images/activated_muscles/female/abdomen/'),
('images/activated_muscles/male/abdomen/'),
('images/activated_muscles/female/biceps/'),
('images/activated_muscles/male/biceps/'),
('images/activated_muscles/female/triceps/'),
('images/activated_muscles/male/triceps/'),
('images/activated_muscles/female/forearm/'),
('images/activated_muscles/male/forearm/'),
('images/activated_muscles/female/shoulder/'),
('images/activated_muscles/male/shoulder/'),
('images/activated_muscles/female/chest/'),
('images/activated_muscles/male/chest/'),
('images/activated_muscles/female/quadriceps/'),
('images/activated_muscles/male/quadriceps/'),
('images/activated_muscles/female/adductor/'),
('images/activated_muscles/male/adductor/'),
('images/activated_muscles/female/trapezius/'),
('images/activated_muscles/male/trapezius/'),
('images/activated_muscles/female/lats/'),
('images/activated_muscles/male/lats/'),
('images/activated_muscles/female/lower_back/'),
('images/activated_muscles/male/lower_back/'),
('images/activated_muscles/female/hamstrings/'),
('images/activated_muscles/male/hamstrings/'),
('images/activated_muscles/female/glutes/'),
('images/activated_muscles/male/glutes/'),
('images/activated_muscles/female/calf/'),
('images/activated_muscles/male/calf/');

INSERT INTO muscle_group (name, fk_male_model_media_ID, fk_female_model_media_ID) VALUES
('Abdômen', 2, 1),
('Bíceps', 4, 3),
('Tríceps', 6, 5),
('Antebraço', 8, 7),
('Ombro', 10, 9),
('Peito', 12, 11),
('Quadríceps', 14, 13),
('Adutor', 16, 15),
('Trapézio', 18, 17),
('Dorsal', 20, 19),
('Lombar', 22, 21),
('Posterior de Coxa', 24, 23),
('Glúteos', 26, 25),
('Panturrilha', 28, 27);

INSERT INTO exercise (name, description, is_fixed, fk_media_ID) VALUES 
('Tríceps Francês', 'Movimento de extensão dos cotovelos com os braços ao lado da cabeça.', 0, NULL),
('Tríceps Pulley', 'Movimento de extensão dos cotovelos com os braços ao lado do tronco.', 0, NULL),
('Tríceps Testa', 'Movimento de extensão dos cotovelos com os braços à frente da cabeça.', 0, NULL),
('Tríceps Coice', 'Movimento de extensão dos cotovelos com o tronco inclinado e os braços ao lado do tronco.', 0, NULL),
('Tríceps Mergulho', 'Movimento de extensão dos cotovelos com flexão dos ombros, realizado com os braços atrás do tronco.', 0, NULL),
('Rosca Punho', 'Movimento de flexão ou extensão dos punhos.', 0, NULL),
('Adução de Punho', 'Movimento de adução dos punhos.', 0, NULL),
('Abdução de Punho', 'Movimento de abdução dos punhos.', 0, NULL),
('Flexão de Dedos', 'Movimento de flexão dos dedos.', 0, NULL),
('Sustentação de Peso com as Mãos', 'Posição em que os dedos estão flexionados para sustentar uma carga.', 0, NULL),
('Roller de Punho', 'Movimento de enrolar e desenrolar uma corda com peso usando os punhos.', 1, NULL),
('Rosca Direta Tradicional', 'Movimento de flexão dos cotovelos com pegada supinada e os braços ao lado do tronco.', 0, NULL),
('Rosca Inversa', 'Movimento de flexão dos cotovelos com pegada pronada e os braços ao lado do tronco.', 0, NULL),
('Rosca Scott Tradicional', 'Movimento de flexão dos cotovelos com pegada supinada e os braços apoiados à frente do tronco.', 0, NULL),
('Rosca Scott Inversa', 'Movimento de flexão dos cotovelos com pegada pronada e os braços apoiados à frente do tronco.', 0, NULL),
('Rosca Aranha', 'Movimento de flexão dos cotovelos com o tronco inclinado para frente.', 0, NULL),
('Rosca Direta Inclinada', 'Movimento de flexão dos cotovelos com os braços atrás do tronco.', 0, NULL), 
('Rosca Concentrada', 'Movimento de flexão dos cotovelos com o braço apoiado ou próximo à parte interna da coxa.', 0, NULL),
('Rosca Cruz', 'Movimento de flexão dos cotovelos com os braços elevados lateralmente.', 0, NULL),
('Supino Reto', 'Movimento de adução horizontal dos ombros com extensão dos cotovelos, realizado com os braços formando um ângulo de aproximadamente 90° em relação ao tronco.', 0, NULL),
('Supino Inclinado', 'Movimento de adução horizontal dos ombros com extensão dos cotovelos, realizado com os braços formando um ângulo de aproximadamente 120° em relação ao tronco.', 0, NULL),
('Supino Declinado', 'Movimento de adução horizontal dos ombros com extensão dos cotovelos, realizado com os braços formando um ângulo menor que 90° em relação ao tronco.', 0, NULL),
('Crucifixo Reto', 'Movimento de adução horizontal dos ombros com os cotovelos ligeiramente flexionados, realizado com os braços formando um ângulo de aproximadamente 90° em relação ao tronco.', 0, NULL),
('Crucifixo Inclinado', 'Movimento de adução horizontal dos ombros com os cotovelos ligeiramente flexionados, realizado com os braços formando um ângulo de aproximadamente 120° em relação ao tronco.', 0, NULL),
('Crucifixo Declinado', 'Movimento de adução horizontal dos ombros com os cotovelos ligeiramente flexionados, realizado com os braços formando um ângulo menor que 90° em relação ao tronco.', 0, NULL),
('Flexão', 'Movimento de adução horizontal e/ou flexão dos ombros com extensão dos cotovelos, realizado com o corpo paralelo ao solo.', 1, NULL),
('Elevação Lateral', 'Movimento de abdução dos ombros com os cotovelos ligeiramente flexionados.', 0, NULL),
('Elevação Frontal', 'Movimento de flexão dos ombros com os cotovelos ligeiramente flexionados.', 0, NULL),
('Crucifixo Inverso', 'Movimento de abdução horizontal dos ombros com os cotovelos ligeiramente flexionados.', 0, NULL),
('Desenvolvimento', 'Movimento de abdução e/ou flexão dos ombros com extensão dos cotovelos.', 0, NULL),
('Remada Alta', 'Movimento de abdução dos ombros com flexão dos cotovelos.', 0, NULL),
('Puxada de Rosto', 'Movimento de abdução horizontal e rotação externa dos ombros com flexão dos cotovelos.', 0, NULL),
('Encolhimento', 'Movimento de elevação da escápula.', 0, NULL),
('Puxada', 'Movimento de adução e/ou extensão dos ombros com flexão dos cotovelos e retração da escápula.', 0, NULL),
('Remada Tradicional', 'Movimento de abdução horizontal e/ou extensão dos ombros com flexão dos cotovelos e retração da escápula, realizado com o tronco inclinado ou apoiado, ou em máquinas.', 0, NULL),
('Remada Cavalinho', 'Movimento de abdução horizontal e/ou extensão dos ombros com flexão dos cotovelos e retração da escápula, realizado com barra ou máquina T-bar, com trajetória angular.', 0, NULL),
('Remada Baixa', 'Movimento de abdução horizontal e/ou extensão dos ombros com flexão dos cotovelos e retração da escápula, realizado sentado em uma polia baixa.', 0, NULL),
('Pulldown', 'Movimento de extensão dos ombros com os cotovelos ligeiramente flexionados, realizado em pé ou sentado.', 0, NULL),
('Pullover', 'Movimento de extensão dos ombros com os cotovelos ligeiramente flexionados, realizado deitado.', 0, NULL),
('Meio Terra', 'Movimento de extensão do quadril com extensão dos joelhos e retração da escápula, realizado com o peso em um apoio sobre o chão.', 0, NULL),
('Extensão Lombar', 'Movimento de extensão da coluna lombar.', 0, NULL),
('Gêmeos em Pé', 'Movimento de flexão plantar dos tornozelos, realizado em pé.', 0, NULL),
('Gêmeos Sentado', 'Movimento de flexão plantar dos tornozelos, realizado sentado.', 0, NULL),
('Gêmeos com Quadril Flexionado', 'Movimento de flexão plantar dos tornozelos com o quadril flexionado.', 0, NULL),
('Mesa Flexora', 'Movimento de flexão dos joelhos, realizado deitado.', 0, NULL),
('Cadeira Flexora', 'Movimento de flexão dos joelhos, realizado sentado.', 0, NULL),
('Flexora em Pé', 'Movimento de flexão dos joelhos, realizado em pé.', 0, NULL),
('Stiff', 'Movimento de extensão do quadril com os joelhos ligeiramente flexionados, realizado com o peso segurado pelas mãos.', 0, NULL),
('Bom Dia', 'Movimento de extensão do quadril com os joelhos ligeiramente flexionados,  realizado com o peso apoiado nas costas.', 0, NULL),
('Flexão Nórdica', 'Movimento de flexão dos joelhos com o quadril ligeiramente flexionado, realizado com os pés presos.', 1, NULL),
('Elevação Pélvica', 'Movimento de extensão do quadril com os joelhos flexionados e as costas apoiadas.', 0, NULL),
('Cadeira Abdutora', 'Movimento de abdução do quadril, realizado sentado em máquina.', 1, NULL),
('Abdução de Quadril em Pé', 'Movimento de abdução do quadril, realizado em pé.', 0, NULL),
('Glúteo Coice', 'Movimento de extensão de quadril com as mãos e/ou braços apoiados.', 0, NULL),
('Búlgaro', 'Movimento de extensão do quadril e dos joelhos com uma perna sobre um apoio atrás do corpo e a outra no chão.', 0, NULL),
('Agachamento Sumô', 'Movimento de extensão do quadril e dos joelhos com os pés afastados, realizado com o peso apoiado nas costas ou cintura.', 0, NULL),
('Levantamento Terra Sumô', 'Movimento de extensão do quadril e dos joelhos com os pés afastados, realizado com o peso segurado pelas mãos.', 0, NULL),
('Levantamento Terra Tradicional', 'Movimento de extensão do quadril e dos joelhos com os pés na largura dos ombros, realizado inicialmente com o quadril baixo e o peso segurado pelas mãos.', 0, NULL),
('Levantamento Terra Romeno', 'Movimento de extensão do quadril e dos joelhos com os pés na largura dos ombros, realizado inicialmente com o quadril alto e o peso segurado pelas mãos.', 0, NULL),
('Cadeira Adutora', 'Movimento de adução do quadril, realizado sentado em máquina.', 1, NULL),
('Adução de Quadril em Pé', 'Movimento de adução do quadril, realizado em pé.', 0, NULL),
('Cadeira Extensora', 'Movimento de extensão dos joelhos, realizado sentado em máquina.', 1, NULL),
('Extensora Deitado', 'Movimento de extensão dos joelhos, realizado deitado em máquina.', 1, NULL),
('Agachamento Tradicional', 'Movimento de extensão do quadril e dos joelhos com os pés na largura dos ombros, realizado com o peso apoiado nas costas ou cintura.', 0, NULL),
('Agachamento Frontal', 'Movimento de extensão do quadril e dos joelhos com os pés na largura dos ombros, realizado com o peso apoiado nos ombros.', 0, NULL),
('Agachamento Romano', 'Movimento de extensão do quadril e dos joelhos com os pés na largura dos ombros, realizado com a panturrilha e pés apoiados.', 1, NULL),
('Leg Press', 'Movimento de extensão do quadril e dos joelhos, realizado sentado ou deitado.', 0, NULL),
('Passada', 'Movimento de extensão do quadril e dos joelhos unilateral e alternadamente.', 1, NULL),
('Afundo', 'Movimento de extensão do quadril e dos joelhos unilateral e com uma perna a aproximadamente dois passos de distância da outra.', 0, NULL),
('Abdominal Supra', 'Movimento de flexão da coluna lombar, realizado com ou sem flexão de quadril.', 0, NULL),
('Abdominal Infra Deitado', 'Movimento de flexão do quadril com o tronco estático, realizado deitado.', 1, NULL),
('Abdominal Infra na Barra Fixa', 'Movimento de flexão do quadril com o tronco estático, realizado em uma barra fixa.', 1, NULL),
('Abdominal Infra Apoiado', 'Movimento de flexão do quadril com o tronco estático, realizado com braços apoiados e costas apoiados.', 1, NULL),
('Prancha', 'Posição em que os joelhos e quadril estão extendidos com a coluna lombar flexionada e os braços apoiados no chão.', 1, NULL),
('Abdominal Bicicleta', 'Movimento de rotação do tronco e flexão do quadril alternadamente com a coluna lombar flexionada.', 1, NULL),
('Abdominal Oblíquo na Barra Fixa', 'Movimento de rotação do tronco e flexão do quadril, realizado em uma barra fixa.', 1, NULL),
('Abdominal Oblíquo Deitado', 'Movimento de rotação do tronco e flexão do quadril, realizado Deitado.', 1, NULL);