INSERT INTO media (url) VALUES
('images/activated_muscles/female/abdomen/'),
('images/activated_muscles/male/abdomen/'),
('images/activated_muscles/female/biceps/'),
('images/activated_muscles/male/biceps/'),
('images/activated_muscles/female/triceps/'),
('images/activated_muscles/male/triceps/'),
('images/activated_muscles/female/forearm/'),
('images/activated_muscles/male/forearm/'),
('images/activated_muscles/female/shoulder/'),
('images/activated_muscles/male/shoulder/'),
('images/activated_muscles/female/chest/'),
('images/activated_muscles/male/chest/'),
('images/activated_muscles/female/quadriceps/'),
('images/activated_muscles/male/quadriceps/'),
('images/activated_muscles/female/adductor/'),
('images/activated_muscles/male/adductor/'),
('images/activated_muscles/female/trapezius/'),
('images/activated_muscles/male/trapezius/'),
('images/activated_muscles/female/lats/'),
('images/activated_muscles/male/lats/'),
('images/activated_muscles/female/lower_back/'),
('images/activated_muscles/male/lower_back/'),
('images/activated_muscles/female/hamstrings/'),
('images/activated_muscles/male/hamstrings/'),
('images/activated_muscles/female/glutes/'),
('images/activated_muscles/male/glutes/'),
('images/activated_muscles/female/calf/'),
('images/activated_muscles/male/calf/'),
('images/cardio_options/elliptical.png'),
('images/cardio_options/recumbent_exercise_bike.png'),
('images/cardio_options/upright_exercise_bike.png'),
('images/cardio_options/rowing_machine.png'),
('images/cardio_options/stair_simulator.png'),
('images/cardio_options/treadmill.png'),
('https://res.cloudinary.com/dt5rj5jsb/video/upload/v1748925660/Triceps_testa_yxt7z2.mp4'),  
('https://res.cloudinary.com/dt5rj5jsb/video/upload/v1748925653/Triceps_pulley_zffryr.mp4'), 
('https://res.cloudinary.com/dt5rj5jsb/video/upload/v1748925651/Triceps_frances_mtiknw.mp4'), 
('https://res.cloudinary.com/dt5rj5jsb/video/upload/v1748925651/Terra_sumo_hp1qgl.mp4'), 
('https://res.cloudinary.com/dt5rj5jsb/video/upload/v1748925651/Triceps_coice_wvytbb.mp4'), 
('https://res.cloudinary.com/dt5rj5jsb/video/upload/v1748925650/Terra_tradicional_nk7ryr.mp4'), 
('https://res.cloudinary.com/dt5rj5jsb/video/upload/v1748925650/Terra_romeno_vbd2ab.mp4'), 
('https://res.cloudinary.com/dt5rj5jsb/image/upload/v1748925649/Sustentacao_peso_qrod0l.jpg'), 
('https://res.cloudinary.com/dt5rj5jsb/video/upload/v1748925643/Supino_reto_qdjzdr.mp4'), 
('https://res.cloudinary.com/dt5rj5jsb/video/upload/v1748925642/Supino_declinado_rcc2cc.mp4'), 
('https://res.cloudinary.com/dt5rj5jsb/video/upload/v1748925642/Supino_inclinado_i9gfon.mp4'), 
('https://res.cloudinary.com/dt5rj5jsb/video/upload/v1748925642/Stiff_sfqpap.mp4'), 
('https://res.cloudinary.com/dt5rj5jsb/video/upload/v1748925640/Rosca_scott_inversa_izd8w9.mp4'), 
('https://res.cloudinary.com/dt5rj5jsb/video/upload/v1748925641/Rosca_scott_tradicional_g1u673.mp4'), 
('https://res.cloudinary.com/dt5rj5jsb/video/upload/v1748925640/Rosca_punho_hxj0ts.mp4'), 
('https://res.cloudinary.com/dt5rj5jsb/video/upload/v1748925640/Rosca_martelo_gs0osy.mp4'), 
('https://res.cloudinary.com/dt5rj5jsb/video/upload/v1748925634/Rosca_inversa_oe7wew.mp4'), 
('https://res.cloudinary.com/dt5rj5jsb/video/upload/v1748925633/Rosca_direta_tradicional_s1e05h.mp4'), 
('https://res.cloudinary.com/dt5rj5jsb/video/upload/v1748925633/Rosca_inclinada_y1hnyz.mp4'), 
('https://res.cloudinary.com/dt5rj5jsb/video/upload/v1748925632/Rosca_concentrada_aqaowu.mp4'), 
('https://res.cloudinary.com/dt5rj5jsb/video/upload/v1748925632/Rosca_cruz_pp2dpz.mp4'), 
('https://res.cloudinary.com/dt5rj5jsb/video/upload/v1748925631/Rosca_aranha_lea6uj.mp4'), 
('https://res.cloudinary.com/dt5rj5jsb/video/upload/v1748925631/Remada_tradicional_o4rqa4.mp4'),
('https://res.cloudinary.com/dt5rj5jsb/video/upload/v1748925631/Roller_punho_lg4qfn.mp4'), 
('https://res.cloudinary.com/dt5rj5jsb/video/upload/v1748925623/Remada_cavalinho_qzrlmc.mp4'), 
('https://res.cloudinary.com/dt5rj5jsb/video/upload/v1748925623/Remada_baixa_hshoxq.mp4'), 
('https://res.cloudinary.com/dt5rj5jsb/video/upload/v1748925622/Remada_alta_sixcx0.mp4'), 
('https://res.cloudinary.com/dt5rj5jsb/video/upload/v1748925622/Puxada_rosto_pk5yn1.mp4'), 
('https://res.cloudinary.com/dt5rj5jsb/video/upload/v1748925622/Puxada_mfhh7x.mp4'), 
('https://res.cloudinary.com/dt5rj5jsb/video/upload/v1748925621/Pullover_pstoot.mp4'), 
('https://res.cloudinary.com/dt5rj5jsb/video/upload/v1748925621/Pulldown_dq9pbt.mp4'), 
('https://res.cloudinary.com/dt5rj5jsb/image/upload/v1748925619/Prancha_acl4lf.jpg'), 
('https://res.cloudinary.com/dt5rj5jsb/video/upload/v1748925617/Passada_kedcfe.mp4'), 
('https://res.cloudinary.com/dt5rj5jsb/video/upload/v1748925615/Mesa_flexora_poo1gf.mp4'), 
('https://res.cloudinary.com/dt5rj5jsb/video/upload/v1748925615/Legpress_kuf419.mp4'), 
('https://res.cloudinary.com/dt5rj5jsb/video/upload/v1748925615/Mergulho_j67ynw.mp4'), 
('https://res.cloudinary.com/dt5rj5jsb/video/upload/v1748925614/Gluteo_coice_ca44c7.mp4'), 
('https://res.cloudinary.com/dt5rj5jsb/video/upload/v1748925614/Gemeos_sentado_xrt4vz.mp4'), 
('https://res.cloudinary.com/dt5rj5jsb/video/upload/v1748925612/Gemeos_quadril_flexionado_u299zm.mp4'), 
('https://res.cloudinary.com/dt5rj5jsb/video/upload/v1748925607/Flexao_dedos_fbpk1n.mp4'), 
('https://res.cloudinary.com/dt5rj5jsb/video/upload/v1748925608/Gemeos_em_pe_eubmjm.mp4'), 
('https://res.cloudinary.com/dt5rj5jsb/video/upload/v1748925608/Flexao_nordica_jajkhz.mp4'), 
('https://res.cloudinary.com/dt5rj5jsb/video/upload/v1748925607/Flexora_em_pe_xocysj.mp4'), 
('https://res.cloudinary.com/dt5rj5jsb/video/upload/v1748925606/Encolhimento_cknaaz.mp4'), 
('https://res.cloudinary.com/dt5rj5jsb/video/upload/v1748925606/Extensao_lombar_fg1lrd.mp4'), 
('https://res.cloudinary.com/dt5rj5jsb/video/upload/v1748925605/Extensora_zfsfgt.mp4'), 
('https://res.cloudinary.com/dt5rj5jsb/video/upload/v1748925605/Flexao_wcpy3f.mp4'), 
('https://res.cloudinary.com/dt5rj5jsb/video/upload/v1748925604/Elevacao_pelvica_wsxe1p.mp4'), 
('https://res.cloudinary.com/dt5rj5jsb/video/upload/v1748925603/Elevacao_lateral_wxmk3t.mp4'), 
('https://res.cloudinary.com/dt5rj5jsb/video/upload/v1748925600/Elevacao_frontal_gjmz77.mp4'), 
('https://res.cloudinary.com/dt5rj5jsb/video/upload/v1748925597/Crucifixo_declinado_mup9zp.mp4'), 
('https://res.cloudinary.com/dt5rj5jsb/video/upload/v1748925599/Desenvolvimento_adr7ek.mp4'), 
('https://res.cloudinary.com/dt5rj5jsb/video/upload/v1748925597/Crucifixo_inclinado_tsj5sx.mp4'), 
('https://res.cloudinary.com/dt5rj5jsb/video/upload/v1748925597/Crucifixo_inverso_ktwz7g.mp4'), 
('https://res.cloudinary.com/dt5rj5jsb/video/upload/v1748925597/Crucifixo_reto_zj82cx.mp4'), 
('https://res.cloudinary.com/dt5rj5jsb/video/upload/v1748925596/Cadeira_flexora_xqfbez.mp4'), 
('https://res.cloudinary.com/dt5rj5jsb/video/upload/v1748925595/Cadeira_adutora_vqszqa.mp4'), 
('https://res.cloudinary.com/dt5rj5jsb/video/upload/v1748925595/Cadeira_abdutora_rgcu9a.mp4'), 
('https://res.cloudinary.com/dt5rj5jsb/video/upload/v1748925591/Bomdia_rl3qyd.mp4'), 
('https://res.cloudinary.com/dt5rj5jsb/video/upload/v1748925589/Agachamento_tradicional_bo8g1b.mp4'), 
('https://res.cloudinary.com/dt5rj5jsb/video/upload/v1748925589/Agachamento_sumo_volatg.mp4'), 
('https://res.cloudinary.com/dt5rj5jsb/video/upload/v1748925588/Agachamento_romano_rohkwz.mp4'), 
('https://res.cloudinary.com/dt5rj5jsb/video/upload/v1748925588/Agachamento_bulgaro_u3qank.mp4'), 
('https://res.cloudinary.com/dt5rj5jsb/video/upload/v1748925588/Agachamento_frontal_wpthvr.mp4'), 
('https://res.cloudinary.com/dt5rj5jsb/video/upload/v1748925587/Afundo_yymijf.mp4'), 
('https://res.cloudinary.com/dt5rj5jsb/video/upload/v1748925588/Aducao_punho_gvuy9h.mp4'),  
('https://res.cloudinary.com/dt5rj5jsb/video/upload/v1748925586/Aducao_em_pe_kcq6yy.mp4'), 
('https://res.cloudinary.com/dt5rj5jsb/video/upload/v1748925580/Adominal_bicicleta_skkysz.mp4'), 
('https://res.cloudinary.com/dt5rj5jsb/video/upload/v1748925578/Abducao_punho_su3fvd.mp4'),  
('https://res.cloudinary.com/dt5rj5jsb/video/upload/v1748925578/Abdominal_obliquo_barra_livre_yxfbeg.mp4'), 
('https://res.cloudinary.com/dt5rj5jsb/video/upload/v1748925578/Abducao_em_pe_wmvtby.mp4'), 
('https://res.cloudinary.com/dt5rj5jsb/video/upload/v1748925577/Abdominal_infra_deitado_psis12.mp4'), 
('https://res.cloudinary.com/dt5rj5jsb/video/upload/v1748925577/Abdominal_escalador_maqxcw.mp4'), 
('https://res.cloudinary.com/dt5rj5jsb/video/upload/v1748925577/Abdominal_infra_barra_fixa_sbaf4p.mp4'), 
('https://res.cloudinary.com/dt5rj5jsb/video/upload/v1748925576/Abdominal_infra_apoiado_gzxptq.mp4'), 
('https://res.cloudinary.com/dt5rj5jsb/video/upload/v1748925576/Abdomina_supra_h4acnu.mp4'), 
('https://res.cloudinary.com/dt5rj5jsb/video/upload/v1748925576/Abdomina_obliquo_deitado_w9lk5h.mp4'); 


INSERT INTO muscle_group (name, fk_male_model_media_ID, fk_female_model_media_ID) VALUES
('Abdômen', 2, 1),
('Bíceps', 4, 3),
('Tríceps', 6, 5),
('Antebraço', 8, 7),
('Ombro', 10, 9),
('Peito', 12, 11),
('Quadríceps', 14, 13),
('Adutor', 16, 15),
('Trapézio', 18, 17),
('Dorsal', 20, 19),
('Lombar', 22, 21),
('Posterior de Coxa', 24, 23),
('Glúteos', 26, 25),
('Panturrilha', 28, 27);

INSERT INTO exercise (name, description, is_fixed, fk_media_ID) VALUES 
('Tríceps Francês', 'Empurre um peso para cima com os braços acima da cabeça. Movimente somente o antebraço.', 0, 37),
('Tríceps Pulley', 'Empurre um peso para baixo com os braços ao lado do tronco em uma polia alta. Movimente somente o antebraço.', 0, 36),
('Tríceps Testa', 'Empurre um peso para frente com os braços à frente da cabeça. Movimente somente o antebraço.', 0, 35),
('Tríceps Coice', 'Empurre um peso para trás com os braços ao lado do tronco inclinado para frente em uma polia alta. Movimente somente o antebraço.', 0, 39),
('Tríceps Mergulho', 'Empurre um peso para baixo com os braços ao lado do tronco. Movimente somente o braço.', 0, 70),
('Rosca Punho', 'Movimente somente um peso com os braços fixos. Utilize somente o punho.', 0, 49), 
('Adução de Punho', 'Movimente somente um peso em direção ao seu dedo mínimo com os braços fixos. Utilize somente o punho.', 0, 100), 
('Abdução de Punho', 'Movimente somente um peso em direção ao seu dedo polegar com os braços fixos. Utilize somente o punho.', 0, 103), 
('Flexão de Dedos', 'Movimento um peso com os braços fixos. Utilize somente os dedos.', 0, 74), 
('Sustentação de Peso com as Mãos', 'Segure e mantenha um peso com as mãos.', 0, 42),
('Roller de Punho', 'Torça e destorça uma barra amarrada a pesos.', 1, 58),
('Rosca Direta Tradicional', 'Puxe um peso para cima com os braços ao lado do tronco e com as palmas das mãos viradas para cima. Movimente somente o antebraço.', 0, 52),
('Rosca Inversa', 'Puxe um peso para cima com os braços ao lado do tronco e com as palmas das mãos viradas para baixo. Movimente somente o antebraço.', 0, 51), 
('Rosca Scott Tradicional', 'Puxe um peso para cima com os braços apoiados à frente do tronco e com as palmas das mãos viradas para cima. Movimente somente o antebraço.', 0, 48),
('Rosca Scott Inversa', 'Puxe um peso para cima com os braços apoiados à frente do tronco e com as palmas das mãos viradas para baixo. Movimente somente o antebraço.', 0, 47),
('Rosca Aranha', 'Puxe um peso para cima com os braços soltos à frente do tronco inclinado para frente. Movimente somente o antebraço.', 0, 56),
('Rosca Direta Inclinada', 'Puxe um peso para cima com os braços atrás do tronco. Movimente somente o antebraço.', 0, 53), 
('Rosca Concentrada', 'Puxe um peso em direção ao peito com os braços à frente do tronco inclinado para frente. Movimente somente o antebraço.', 0, 54),
('Rosca Cruz', 'Puxe um peso em direção à cabeça com os braços ao lado dela. Movimente somente o antebraço.', 0, 55),
('Supino Reto', 'Empurre um peso para frente do tronco. Movimente somente o braço.', 0, 43),
('Supino Inclinado', 'Empurre um peso para frente e para cima do tronco. Movimente somente o braço.', 0, 45),
('Supino Declinado', 'Empurre um peso para frente e para baixo do tronco. Movimente somente o braço.', 0, 44),
('Crucifixo Reto', 'Junte os seus braços à frente do tronco com eles levemente dobrados. Movimente somente o braço.', 0, 89),
('Crucifixo Declinado', 'Junte os seus braços à frente do tronco e próximo as pernas com eles levemente dobrados. Movimente somente o braço.', 0, 85),
('Crucifixo Inclinado', 'Junte os seus braços à frente do tronco e mais próximos à cabeça com eles levemente dobrados. Movimente somente o braço.', 0, 87),
('Flexão', 'Deite no chão de bruços e empurre o seu próprio corpo. Movimente somente o braço.', 1, 81),
('Elevação Lateral', 'Levante os seus braços ao lado do tronco com eles levemente dobrados. Movimente somente o braço.', 0, 83),
('Elevação Frontal', 'Levante os seus braços à frente do tronco com eles levemente dobrados. Movimente somente o braço.', 0, 84),
('Crucifixo Inverso', 'Puxe um peso em direção as costas com os seus braços na altura dos ombros e levemente dobrados. Movimente somente o braço.', 0, 88),
('Desenvolvimento', 'Empurre um peso para cima da cabeça. Movimente somente o braço.', 0, 86),
('Remada Alta', 'Puxe um peso para cima até a altura do peito. Movimente somente o braço.', 0,61),
('Puxada de Rosto', 'Puxe um peso em direção a cabeça com os braços na altura dos ombros. Movimente somente o braço e o ombro.', 0, 62),
('Encolhimento', 'Suba os seus ombros com eles e os braços fixos.', 0, 78),
('Puxada', 'Puxe um peso até a altura do pescoço com os braços acima da cabeça. Movimente somente o braço e o ombro.', 0, 63),
('Remada Tradicional', 'Puxe um peso em direção ao tronco, estando apoiado, com ele inclinado, ou em máquinas. Movimente somente o braço e o ombro.', 0, 57),
('Remada Cavalinho', 'Puxe um peso em direção ao tronco, estando apoiado ou com ele inclinado em máquina T-bar, com trajetória angular. Movimente somente o braço e o ombro.', 0, 59),
('Remada Baixa', 'Puxe um peso em direção ao tronco, estando sentado e em uma polia baixa. Movimente somente o braço e o ombro.', 0, 60), 
('Pulldown', 'Puxe um peso até a altura do umbigo com os braços levemente dobrados e alinhados com os ombros, com trajetória angular. Movimente somente o braço e o ombro.', 0, 65),
('Pullover', 'Puxe um peso até a altura do peito com os braços levemente dobrados e alinhados com os ombros, com trajetória angular, estando deitado. Movimente somente o braço e o ombro.', 0, 64),
('Extensão Lombar', 'Levante o seu tronco e extenda sua coluna com as pernas presas em um banco romano. Movimente somente o tronco e a coluna.', 0, 79),
('Rosca Martelo', 'Puxe um peso para cima com os braços ao lado do tronco e com as palmas das mãos voltadas ára o tronco. Movimente somente o antebraço.', 0, 50),
('Gêmeos em Pé', 'Apoie a ponta dos pés deixando o calcanhar suspenso, estando em pé. Movimente somente o calcanhar.', 0, 75),
('Gêmeos Sentado', 'Apoie a ponta dos pés deixando o calcanhar suspenso, estando sentado com as pernas dobradas. Movimente somente o calcanhar.', 0, 72),
('Gêmeos com Quadril Flexionado', 'Apoie a ponta dos pés deixando o calcanhar suspenso, estando sentado com as pernas esticadas. Movimente somente o calcanhar.', 0, 73),
('Mesa Flexora', 'Puxe um peso com ele apoiado nos pés ou na parte de trás da canela, estando deitado. Movimente somente o joelho.', 0, 68),
('Cadeira Flexora', 'Puxe um peso com ele apoiado na parte de trás da canela, estando sentado. Movimente somente o joelho.', 0, 90),
('Flexora em Pé', 'Puxe um peso com ele apoiado na parte de trás da canela, estando em pé. Movimente somente o joelho.', 0, 77),
('Stiff', 'Levante um peso do chão com as mãos e com as pernas levemente dobradas. Movimente somente o quadril.', 0, 46), 
('Bom Dia', 'Levante um peso apoiado nas costas com as pernas levemente dobradas. Movimente somente o quadril.', 0, 93),
('Flexão Nórdica', 'Com os pés presos e canela apoiada, desça e suba as pernas com o quadril levemente dobrado. Movimente somente o joelho.', 0, 76),
('Elevação Pélvica', 'Suba um peso com ele apoiado no quadril e as costas e sola dos pés apoiados, estando deitado. Movimente somente o quadril.', 0, 82),
('Cadeira Abdutora', 'Abra as pernas com a parte lateral da coxa apoiada, estando sentado. Movimente somente a perna.', 1, 92),
('Abdução de Quadril em Pé', 'Abra as pernas com o peso preso ou apoiado no calcanhar, estando em pé. Movimente somente a perna.', 0, 105), 
('Glúteo Coice', 'Empurre um peso para trás do corpo com as pernas. Movimente somente a perna.', 0, 71),
('Búlgaro', 'Agache com uma única perna, estando com o pé da outra perna apoiada em um banco atrás do tronco. Movimente somente a perna e o quadril.', 0, 97),
('Agachamento Sumô', 'Agache com as pernas bem afastadas. Movimente somente a perna e o quadril.', 0, 95),
('Levantamento Terra Sumô', 'Levante um peso do chão com as mãos e com as pernas bem afastadas. Movimente somente o quadril e a perna.', 0, 38),
('Levantamento Terra Tradicional', 'Levante um peso do chão com as mãos, e com as pernas na largura dos ombros. Movimente somente o quadril e a perna.', 0, 40),
('Levantamento Terra Romeno', 'Levante um peso do chão com as mãos e com o quadril mais alto do que no levantamento terra tradicional. Movimente somente o quadril e a perna.', 0, 41),
('Cadeira Adutora', 'Feche as pernas com a parte interna da coxa apoiada, estando sentado. Movimente somente a perna.', 1, 91),
('Adução de Quadril em Pé', 'Feche as pernas com o peso preso ou apoiado no calcanhar, estando em pé. Movimente somente a perna.', 0, 101),
('Cadeira Extensora', 'Empurre o peso em um movimento de chute, estando sentado ou deitado. Movimente somente o joelho.', 0, 80), 
('Agachamento Tradicional', 'Agache com as pernas na largura dos ombros e o peso apoiado nas costas ou segurado com as mãos. Movimente somente a perna e o quadril.', 0, 94),
('Agachamento Frontal', 'Agache com as pernas na largura dos ombros e o peso apoiado nos ombros à frente do tronco. Movimente somente a perna e o quadril.', 0, 98),
('Agachamento Romano', 'Agache com as pernas na largura dos ombros com os pés presos e panturrilha apoiada. Movimente somente a perna e o quadril.', 1, 96), 
('Leg Press', 'Empurre uma plataforma com peso utilizando as pernas, estando sentado ou deitado. Movimente somente a perna.', 0, 69),
('Passada', 'Simule uma caminhada com passos largos e agachando com a perna da frente a cada passo. Movimente somente a perna e o quadril.', 1, 67),
('Afundo', 'Agache com uma única perna, estando com o pé da outra perna apoiado no chão atrás do tronco. Movimente somente a perna e o quadril.', 0, 99),
('Abdominal Escalador', 'Deite de bruços e fique levantado com seus braços apoiados no chão enquanto tenta encostar suas pernas no seu peito. Movimente somente as pernas.', 1, 107),
('Abdominal Supra', 'Deite com a barriga virada para cima, dobre as pernas e suba seu tronco dobrando a coluna. Movimente somente o tronco e a coluna.', 0, 110),
('Abdominal Infra Deitado', 'Deite com a barriga virada para cima e suba as pernas dobrando a coluna. Movimente somente a perna e a coluna.', 1, 106), 
('Abdominal Infra na Barra Fixa', 'Segure em uma barra fixa e suba as pernas dobrando a coluna. Movimente somente a perna e a coluna.', 1, 108),
('Abdominal Infra Apoiado', 'Apoie seus braços e costas e suba as pernas dobrando a coluna. Movimente somente a perna e a coluna.', 1, 109),
('Prancha', 'Deite de bruços e fique levantado com seus braços apoiados no chão com tronco e pernas alinhados.', 1, 66),
('Abdominal Bicicleta', 'Deite com a barriga virada para cima com as pernas e coluna dobradas simulando uma pedalada. Rotacione o tronco e movimente somente a perna.', 1, 102),
('Abdominal Oblíquo na Barra Fixa', 'Segure em uma barra fixa e suba as pernas dobrando a coluna e rotacionando o tronco. Rotacione o tronco e movimente somente a perna e a coluna.', 1, 104),
('Abdominal Oblíquo Deitado', 'Deite com a barriga virada para cima, dobre as pernas e suba seu tronco enquanto o rotaciona dobrando a coluna. Rotacione o tronco e movimente somente o tronco e a coluna.', 1, 111);

INSERT INTO exercise_muscle_group (is_primary, fk_exercise_ID, fk_muscle_group_ID) VALUES
(TRUE, 1, 3),
(TRUE, 2, 3),
(TRUE, 3, 3), 
(TRUE, 4, 3),
(TRUE, 5, 3), (FALSE, 5, 6), (FALSE, 5, 5),
(TRUE, 6, 4),
(TRUE, 7, 4),
(TRUE, 8, 4),
(TRUE, 9, 4),
(TRUE, 10, 4), (FALSE, 10, 9),
(TRUE, 11, 4),
(TRUE, 12, 2), (FALSE, 12, 4),
(TRUE, 13, 4), (FALSE, 13, 2),
(TRUE, 14, 2), (FALSE, 14, 4),
(TRUE, 15, 4), (FALSE, 15, 2),
(TRUE, 16, 2), (FALSE, 16, 4),
(TRUE, 17, 2), (FALSE, 17, 4),
(TRUE, 18, 2), (FALSE, 18, 4),
(TRUE, 19, 2), (FALSE, 19, 4),
(TRUE, 20, 6), (FALSE, 20, 5), (TRUE, 20, 3),
(TRUE, 21, 6), (TRUE, 21, 5), (TRUE, 21, 3),
(TRUE, 22, 6), (FALSE, 22, 5), (FALSE, 22, 3),
(TRUE, 23, 6), (FALSE, 23, 5),
(TRUE, 24, 6), (TRUE, 24, 5),
(TRUE, 25, 6), (FALSE, 25, 5),
(TRUE, 26, 6), (TRUE, 26, 5), (TRUE, 26, 3),
(TRUE, 27, 5),
(TRUE, 28, 5), (FALSE, 28, 6),
(TRUE, 29, 5), (FALSE, 29, 9),
(TRUE, 30, 5), (FALSE, 30, 6), (TRUE, 30, 3),
(TRUE, 31, 5), (TRUE, 31, 9),
(TRUE, 32, 5), (TRUE, 32, 9),
(TRUE, 33, 9), (FALSE, 33, 4),
(TRUE, 34, 10), (FALSE, 34, 9), (FALSE, 34, 2),
(TRUE, 35, 10), (TRUE, 35, 9), (FALSE, 35, 2), (FALSE, 35, 4), (FALSE, 35, 11),
(TRUE, 36, 10), (TRUE, 36, 9), (FALSE, 36, 2), (FALSE, 36, 4), (FALSE, 36, 11),
(TRUE, 37, 10), (TRUE, 37, 9), (FALSE, 37, 2), (FALSE, 37, 4), (FALSE, 37, 11),
(TRUE, 38, 10),
(TRUE, 39, 10),
(TRUE, 40, 11), (FALSE, 40, 13),
(TRUE, 41, 2), (TRUE, 41, 4),
(TRUE, 42, 14),
(TRUE, 43, 14),
(TRUE, 44, 14),
(TRUE, 45, 12), (FALSE, 45, 14),
(TRUE, 46, 12), (FALSE, 46, 14),
(TRUE, 47, 12), (FALSE, 47, 14),
(TRUE, 48, 12), (TRUE, 48, 13), (TRUE, 48, 11), (FALSE, 48, 9),
(TRUE, 49, 12), (TRUE, 49, 13), (TRUE, 49, 11),
(TRUE, 50, 12), (FALSE, 50, 14),
(TRUE, 51, 13), (FALSE, 51, 12), (FALSE, 51, 11), (FALSE, 51, 7),
(TRUE, 52, 13),
(TRUE, 53, 13),
(TRUE, 54, 13), (FALSE, 54, 12),
(TRUE, 55, 7), (TRUE, 55, 13), (FALSE, 55, 12),
(TRUE, 56, 13), (TRUE, 56, 7), (FALSE, 56, 8), (FALSE, 56, 11),
(TRUE, 57, 13), (TRUE, 57, 7), (FALSE, 57, 8), (FALSE, 57, 9), (FALSE, 57, 11),
(TRUE, 58, 13), (FALSE, 58, 7), (FALSE, 58, 8), (FALSE, 58, 12), (FALSE, 58, 9), (FALSE, 58, 11),
(TRUE, 59, 13), (TRUE, 59, 11), (TRUE, 59, 12), (FALSE, 59, 9), (FALSE, 59, 10),
(TRUE, 60, 8),
(TRUE, 61, 8),
(TRUE, 62, 7),
(TRUE, 63, 7), (TRUE, 63, 13), (FALSE, 63, 8), (FALSE, 63, 11),
(TRUE, 64, 7), (FALSE, 64, 13), (FALSE, 64, 8), (FALSE, 64, 11),
(TRUE, 65, 7), (FALSE, 65, 13),
(TRUE, 66, 7), (TRUE, 66, 13), (FALSE, 66, 12),
(TRUE, 67, 7), (FALSE, 67, 13),
(TRUE, 68, 7), (FALSE, 68, 13),
(TRUE, 69, 1),
(TRUE, 70, 1),
(TRUE, 71, 1),
(TRUE, 72, 1), (FALSE, 72, 4),
(TRUE, 73, 1),
(TRUE, 74, 1),
(TRUE, 75, 1),
(TRUE, 76, 1), (FALSE, 76, 4),
(TRUE, 77, 1);

INSERT INTO body_position (description) VALUES
('Em pé'),
('Em pé com o tronco inclinado'),
('Sentado'),
('Sentado no banco reto (de costas para o banco)'),
('Sentado no banco reto (virado para o banco)'),
('Sentado no banco inclinado a 75° (de costas para o banco)'),
('Sentado no banco inclinado a 75° (virado para o banco)'),
('Sentado no banco inclinado a 60° (de costas para o banco)'),
('Sentado no banco inclinado a 60° (virado para o banco)'),
('Deitado no banco inclinado a 45° (de costas)'),
('Deitado no banco inclinado a 45° (de bruços)'),
('Deitado no banco inclinado a 30° (de costas)'),
('Deitado no banco inclinado a 30° (de bruços)'),
('Deitado no banco inclinado a 15° (de costas)'),
('Deitado no banco inclinado a 15° (de bruços)'),
('Deitado no banco não inclinado (de costas)'),
('Deitado no banco não inclinado (de bruços)'),
('Deitado no banco declinado a 15° (de costas)'),
('Deitado no banco declinado a 15° (de bruços)'),
('Deitado no banco declinado a 30° (de costas)'),
('Deitado no banco declinado a 30° (de bruços)'),
('Deitado no banco declinado a 45° (de costas)'),
('Deitado no banco declinado a 45° (de bruços)'),
('Deitado no chão (de costas)'),
('Deitado no chão (de bruços)');

INSERT INTO exercise_equipment (name, description) VALUES 
('Halteres', 'Pesos livres usados com uma única mão.'),
('Barra Livre', 'Barra reta, W, H ou barra hexagonal.'),
('Barra Guiada', 'Barra fixada no aparelho Smith.'),
('Máquina', 'Aparelho guiado com anilhas ou placas de peso.'),
('Livre', 'Exercício com o peso do próprio corpo.'),
('Polia', 'Equipamento com polias e diversos acessórios.'),
('Elástico', 'Faixas que resistem ou ajudam o movimento.'),
('Caneleira', 'Pesos presos nos tornozelos ou pulsos.');

INSERT INTO pulley_height (description) VALUES 
('Altura dos pés'),
('Altura da canela'),
('Altura da coxa'),
('Altura do abdômen'),
('Altura do peito'),
('Altura da cabeça'),
('Altura máxima');

INSERT INTO pulley_attachment (name) VALUES
('Barra Reta'),
('Barra W'),
('Barra H'),
('Barra Triângulo'),
('Barra Anatômica'),
('Corda Curta'),
('Corda Longa'),
('Puxador'),
('Tornozeleira');

INSERT INTO grip_type (name) VALUES
('Pronada'),
('Semi-Pronada'),
('Neutra'),
('Semi-Supinada'),
('Supinada'),
('Pronando'),
('Supinando');

INSERT INTO grip_width (description) VALUES
('Fechada'),
('Média'),
('Aberta');

INSERT INTO laterality (type) VALUES
('Bilateral'),
('Unilateral'),
('Alternado');

INSERT INTO training_technique (name, description) VALUES 
('Drop Set', 'Duas ou mais reduções de carga toda vez que atingir a falha em uma série.'),
('Rest-Pause', 'Duas ou mais pausas curtas toda vez que atingir a falha em uma série.'),
('Parciais Pós-Série', 'Repetições parciais após atingir a falha em uma série.'),
('Parciais Fase Alongada', 'Repetições parciais no ponto de maior alongamento do movimento.'),
('Parciais Fase Contraída', 'Repetições parciais no ponto de maior contração do movimento.'),
('Repetições Forçadas', 'Repetições realizadas com ajuda após atingir a falha em uma série.'),
('Repetições Negativas', 'Repetições realizadas com ajuda na fase concêntrica do movimento.'),
('Cluster Set', 'Pequenas divisões de uma série com pausas curtas entre elas.'),
('FST-7', 'Sete séries com pausas curtas entre elas e mantendo um alongamento do músculo alvo durante os descansos.'),
('Dead Stop', 'Repetições com um descanso no ponto de maior alongamento do movimento.'),
('Pico de Concentração', 'Repetições com uma pausa no ponto de maior contração do movimento.'),
('Ponto Zero', 'Repetições com uma pausa no ponto de maior alongamento do movimento.');

INSERT INTO set_type (name, description, intensity_level) VALUES 
('Aquecimento', 'Série de baixa intensidade com o objetivo de lubrificar articulações, ativar os músculos-alvo e aprimorar a conexão neuromuscular.', 2),
('Preparatória', 'Série de intensidade moderada utilizada para ajustar a carga das séries principais e reduzir o risco de lesões.', 3),
('Trabalho', 'Série efetiva com intensidade suficiente para alcançar ou se aproximar da falha concêntrica dentro da faixa de repetições prescrita.', 4),
('Top', 'Série efetiva com intensidade máxima, realizada até a falha concêntrica ou técnica, dentro da faixa de repetições prescrita.', 5);

INSERT INTO cardio_option (name, fk_media_ID) VALUES
('Esteira', 34),
('Bicicleta Ergométrica Horizontal', 30),
('Bicicleta Ergométrica Vertical', 31),
('Elíptico', 29),
('Remo Seco', 32),
('Simulador de Escada', 33);

INSERT INTO cardio_intensity (type, description, intensity_level) VALUES
('Zona 1', 'Utilização de 50-60% da frequência cardíaca máxima.', 1),
('Zona 2', 'Utilização de 60-70% da frequência cardíaca máxima.', 2),
('Zona 3', 'Utilização de 70-80% da frequência cardíaca máxima.', 3),
('Zona 4', 'Utilização de 80-90% da frequência cardíaca máxima.', 4),
('Zona 5', 'Utilização de 90-100% da frequência cardíaca máxima.', 5),
('HIIT', 'Treino intervalado com períodos alternados de alta e baixa intensidade.', 4);

INSERT INTO contract_status (name) VALUES 
('Ativo'),
('Vencido'),
('Cancelado'),
('Rescindido');
