import os
from datetime import timedelta

class AppConfig:
    SECRET_KEY = os.getenv("SECRET_KEY")

    JWT_SECRET_KEY = os.getenv("JWT_SECRET_KEY")
    JWT_TOKEN_LOCATION = [os.getenv("JWT_TOKEN_LOCATION")]
    JWT_COOKIE_SECURE = os.getenv("JWT_COOKIE_SECURE").lower() == "true"
    JWT_ACCESS_COOKIE_PATH = os.getenv("JWT_ACCESS_COOKIE_PATH")
    JWT_REFRESH_COOKIE_PATH = os.getenv("JWT_REFRESH_COOKIE_PATH")
    JWT_COOKIE_CSRF_PROTECT = os.getenv("JWT_COOKIE_CSRF_PROTECT").lower() == "true"
    JWT_ACCESS_TOKEN_EXPIRES = timedelta(minutes=int(os.getenv("JWT_ACCESS_TOKEN_EXPIRES")))
    JWT_REFRESH_TOKEN_EXPIRES = timedelta(days=int(os.getenv("JWT_REFRESH_TOKEN_EXPIRES")))
    JWT_COOKIE_SAMESITE = os.getenv("JWT_COOKIE_SAMESITE") 
    JWT_ACCESS_COOKIE_NAME = os.getenv("JWT_ACCESS_COOKIE_NAME")
    JWT_REFRESH_COOKIE_NAME = os.getenv("JWT_REFRESH_COOKIE_NAME")

class SQLAlchemyConfig:
    DB_URL = os.getenv("MYSQL_URL")

    if DB_URL and DB_URL.startswith("mysql://"):
        DB_URL = DB_URL.replace("mysql://", "mysql+pymysql://")

    SQLALCHEMY_DATABASE_URI = DB_URL

class CloudinaryConfig:
    settings = {
        "cloud_name": os.getenv("CLOUDINARY_CLOUD_NAME"),
        "api_key": os.getenv("CLOUDINARY_API_KEY"),
        "api_secret": os.getenv("CLOUDINARY_API_SECRET")
    }

class FernetConfig:
    key = os.getenv("FERNET_KEY").encode()

class RedisConfig:  
    settings = {
        "host": os.getenv("REDISHOST"),
        "port": int(os.getenv("REDISPORT")),
        "db": 0,
        "password": os.getenv("REDISPASSWORD"),
        "decode_responses": True
    }  

class CORSConfig:
    settings= {
        "supports_credentials": True,
        "origins": [os.getenv("FRONT_END_URL")],
        "methods": ["GET", "POST", "PUT", "DELETE"],
        "allow_headers": ["Content-Type", "Authorization"]
    }

class OpenaiConfig:
    OPENAI_API_KEY = os.getenv("OPENAI_API_KEY")

class MercadopagoConfig:
    MP_CLIENT_ID = os.getenv("MP_CLIENT_ID")
    MP_REDIRECT_URI = os.getenv("MP_REDIRECT_URI")
    MP_CLIENT_SECRET = os.getenv("MP_CLIENT_SECRET")
    MP_CLIENT_ACCESS_TOKEN = os.getenv("MP_CLIENT_ACCESS_TOKEN")

class SendGridConfig:
    SENDGRID_API_KEY = os.getenv("SENDGRID_API_KEY")
    SENDGRID_TEMPLATE_CONFIRMATION = os.getenv("SENDGRID_TEMPLATE_CONFIRMATION")
    SENDGRID_SENDER_EMAIL = os.getenv("SENDGRID_SENDER_EMAIL")
    SENDGRID_TEMPLATE_CANCEL_CLIENT_CONTRACT_FOR_CLIENT = os.getenv("SENDGRID_TEMPLATE_CANCEL_CLIENT_CONTRACT_FOR_CLIENT")
    SENDGRID_TEMPLATE_CANCEL_CLIENT_CONTRACT_FOR_TRAINER = os.getenv("SENDGRID_TEMPLATE_CANCEL_CLIENT_CONTRACT_FOR_TRAINER")
    SENDGRID_TEMPLATE_CANCEL_TRAINER_CONTRACT_FOR_CLIENT = os.getenv("SENDGRID_TEMPLATE_CANCEL_TRAINER_CONTRACT_FOR_CLIENT")
    SENDGRID_TEMPLATE_CANCEL_TRAINER_CONTRACT_FOR_TRAINER = os.getenv("SENDGRID_TEMPLATE_CANCEL_TRAINER_CONTRACT_FOR_TRAINER")
    SENDGRID_TEMPLATE_CANT_CONTRACT_IN_CONTRACT = os.getenv("SENDGRID_TEMPLATE_CANT_CONTRACT_IN_CONTRACT")
    SENDGRID_TEMPLATE_CANT_CONTRACT_TRAINER_FOR_CLIENT = os.getenv("SENDGRID_TEMPLATE_CANT_CONTRACT_TRAINER_FOR_CLIENT")
    SENDGRID_TEMPLATE_CANT_CONTRACT_TRAINER_FOR_TRAINER = os.getenv("SENDGRID_TEMPLATE_CANT_CONTRACT_TRAINER_FOR_TRAINER")
    SENDGRID_TEMPLATE_MODIFY_CLIENT = os.getenv("SENDGRID_TEMPLATE_MODIFY_CLIENT")
    SENDGRID_TEMPLATE_MODIFY_TRAINER = os.getenv("SENDGRID_TEMPLATE_MODIFY_TRAINER")
    SENDGRID_TEMPLATE_CREATE_TRAINER = os.getenv("SENDGRID_TEMPLATE_CREATE_TRAINER")
    SENDGRID_TEMPLATE_CREATE_ACCOUNT = os.getenv("SENDGRID_TEMPLATE_CREATE_ACCOUNT")
    SENDGRID_TEMPLATE_CONTRACTS_PAUSED = os.getenv("SENDGRID_TEMPLATE_CONTRACTS_PAUSED")
    SENDGRID_TEMPLATE_CONTRACTS_UNPAUSED = os.getenv("SENDGRID_TEMPLATE_CONTRACTS_UNPAUSED")
    SENDGRID_TEMPLATE_DELETE_TRAINING_PLAN = os.getenv("SENDGRID_TEMPLATE_DELETE_TRAINING_PLAN")
    SENDGRID_TEMPLATE_TRAINER_MODIFIED_TRAINING_PLAN_FOR_CLIENT = os.getenv("SENDGRID_TEMPLATE_TRAINER_MODIFIED_TRAINING_PLAN_FOR_CLIENT")
    SENDGRID_TEMPLATE_TRAINER_MODIFIED_PAYMENT_PLAN_FOR_TRAINER = os.getenv("SENDGRID_TEMPLATE_TRAINER_MODIFIED_PAYMENT_PLAN_FOR_TRAINER")
    SENDGRID_TEMPLATE_DELETE_PAYMENT_PLAN = os.getenv("SENDGRID_TEMPLATE_DELETE_PAYMENT_PLAN")
    SENDGRID_TEMPLATE_CREATE_RATING_FOR_CLIENT = os.getenv("SENDGRID_TEMPLATE_CREATE_RATING_FOR_CLIENT")
    SENDGRID_TEMPLATE_CREATE_COMPLAINT_FOR_CLIENT = os.getenv("SENDGRID_TEMPLATE_CREATE_COMPLAINT_FOR_CLIENT")
    SENDGRID_TEMPLATE_CONNECT_MP = os.getenv("SENDGRID_TEMPLATE_CONNECT_MP")
    SENDGRID_TEMPLATE_CLIENT_DELETED_TRAINING_PLAN_FOR_CLIENT = os.getenv("SENDGRID_TEMPLATE_CLIENT_DELETED_TRAINING_PLAN_FOR_CLIENT")
    SENDGRID_TEMPLATE_CANT_DELETE_ACCOUNT_IN_CONTRACT_FOR_TRAINER = os.getenv("SENDGRID_TEMPLATE_CANT_DELETE_ACCOUNT_IN_CONTRACT_FOR_TRAINER")
    SENDGRID_TEMPLATE_DELETED_ACCOUNT = os.getenv("SENDGRID_TEMPLATE_DELETED_ACCOUNT")
    SENDGRID_TEMPLATE_WELCOME_AGAIN = os.getenv("SENDGRID_TEMPLATE_WELCOME_AGAIN")
    SENDGRID_TEMPLATE_DEACTIVATE_PROFILE = os.getenv("SENDGRID_TEMPLATE_DEACTIVATE_PROFILE")
    SENDGRID_TEMPLATE_MODIFIED_PASSWORD = os.getenv("SENDGRID_TEMPLATE_MODIFIED_PASSWORD")
    SENDGRID_TEMPLATE_LOGIN_FAILED = os.getenv("SENDGRID_TEMPLATE_LOGIN_FAILED")
    SENDGRID_TEMPLATE_NEW_CONTRACT_FOR_CLIENT = os.getenv("SENDGRID_TEMPLATE_NEW_CONTRACT_FOR_CLIENT")
    SENDGRID_TEMPLATE_NEW_CONTRACT_FOR_TRAINER = os.getenv("SENDGRID_TEMPLATE_NEW_CONTRACT_FOR_TRAINER")
    SENDGRID_TEMPLATE_NEW_CONTRACT_FAILED_FOR_CLIENT = os.getenv("SENDGRID_TEMPLATE_NEW_CONTRACT_FAILED_FOR_CLIENT")

class ExamplesData:
    EXAMPLE_DEFAULT_PASSWORD = os.getenv("EXAMPLE_DEFAULT_PASSWORD")
    EXAMPLE_FIRST_CLIENT_EMAIL = os.getenv("EXAMPLE_FIRST_CLIENT_EMAIL")
    EXAMPLE_SECOND_CLIENT_EMAIL = os.getenv("EXAMPLE_SECOND_CLIENT_EMAIL")
    EXAMPLE_FIRST_TRAINER_EMAIL = os.getenv("EXAMPLE_FIRST_TRAINER_EMAIL")